21.exe: 21.o Point.o Line.o Random.o RandomLine.o
	g++ -g -o 21.exe 21.o Point.o Line.o Random.o RandomLine.o
21.o: 21.cpp
	g++ -g -c 21.cpp
Point.o: Point.cpp
	g++ -g -c Point.cpp
Line.o: Line.cpp
	g++ -g -c Line.cpp
Random.o: Random.cpp
	g++ -g -c Random.cpp
RandomLine.o: RandomLine.cpp
	g++ -g -c RandomLine.cpp
